### PR TITLE
KRACOEUS-8870 : Fix cost_element sql to use 'Y' as active

### PR DESCRIPTION
**Pull request by blackcathacker**
This is rewriting "historical" scripts which is bad, but I'm not sure how else to fix it. 'N' is considered inactive by current customer databases and implementors, but this script is inserting them as 'N' when they should be active. Any other ideas that won't muck with existing customers/on-prem?

If we do merge this we'll need to reset the kc-qa database tonight to make sure Flyway errors don't kill it.

### CODE REVIEW

**Comment by gathreya** [comment]
Why cannot you just do an update now?

**Comment by blackcathacker** [comment]
update cost_element set actv_flag = 'Y' where actv_flag = 'N'? That would mean reactivating any inactive records in prod databases.

**Comment by gathreya** [comment]
or you can just selectively change the costelement values in that list right?

**Comment by blackcathacker** [comment]
Even doing it for each cost_element id is potentially dangerous as those could have been made intentionally inactive.

**Comment by blackcathacker** [comment]
I suppose I could do an update in staged data? We would never apply stage scripts to prod databases?

**Comment by gathreya** [comment]
I do not think people apply staging data to prod databases. It is meant only for people to test and play with the system.

**Comment by blackcathacker** [comment]
Ok. I'll do that instead.

**Comment by gathreya** [comment]
but cannot you just update those specific cost elemts?

**Comment by blackcathacker** [comment]
Modified to only update specific cost elements in a new demo data script.

**Comment by gathreya** [comment]
Sweet. So my PR references the file with SQL number 13 and this one has file 14. Should I wait for that to br merged before merging this?

**Pull request merged**
