### PR TITLE
KRACOEUS-8813: fixing wilcard search

### PR DESCRIPTION
**Pull request by leoherbie**

### CODE REVIEW

**Comment by leoherbie** [comment]
I'm using the kns legacy data adapter because JPA based search perform so badly with wildcards that the connection times out.

**Comment by gathreya** [comment]
Hey, so you changed it from businessObjectService to knsLegacyAdapter it looks like. Both use OJB right? But your comments seems to indicate you switched from JPA to OJB. What am I missing?

**Comment by leoherbie** [comment]
Right so the issue is that knsLegacyDataAdapter.findCollectionBySearchHelper supports wildcards in criteria values.  Normally you would go through the LookupService which would choose either the krad version (JPA) or the kns version (OJB).  I tried the LookupService but the JPA version performed so poorly that I am explicitly using the kns version.  I can't use businessObjectService because wildcard support isn't there in find matching.

**Comment by leoherbie** [comment]
I didn't switch from JPA to OJB but rather I tried to use JPA and could so I switched back to OJB.

**Pull request merged**
