### PR TITLE
RESKC-195: fixing int tests for the grm profile

### PR DESCRIPTION
**Pull request by leoherbie**

### CODE REVIEW

**Comment by leoherbie** [comment]
this is an alternative fix: https://github.com/KualiCo/kc/pull/165

**Comment by leoherbie** [comment]
Don't merge until we figure out which way we want to do this

**Comment by gathreya** [comment]
Does this fix the issue of the app not starting up also? I am only seeing test related changes.

**Comment by leoherbie** [comment]
This only fixes the tests.  The app should startup fine

**Comment by gathreya** [comment]
Oh, was there another Pr to fix the app startup?

**Comment by leoherbie** [comment]
I have rethought this fix.  I think this has several advantages. 
1) not introducing another config file format 
2) not filtering the web.xml 
3) The KcBootstrapSpringBeans.xml file is not referring to a config file that only exists in the coeus-webapp module 
4) no longer using rice's context initializer which enables us to remove some irrelevant/broken startup logic.

**Comment by blackcathacker** [comment]
Looks good to me. Dunno if I agree that a properties file is a new "config file format". I am curious why we still don't want the build file in the coeus-impl project? Since these are build time properties that define things like dependencies, what wrong with using a single file in the coeus-impl jar instead of relying on different files in the coeus-it and coeus-webapp module? Just seems better and more simple to rely on a single config file than scattering these build files around. And it will define how the coeus-impl jar was built which still seems very reasonable.

**Comment by leoherbie** [comment]
Ideally, I'd like the coeus-impl module to not have to be rebuilt to change a config item.  Right now it has to due to dependencies but I didn't want to add more to that.  I'd like to move the dependency stuff but I didn't want to for this PR.  Regarding the config file format.  I really don't like the complexity of the rice way of configuring things however I thought we should stick with it until we can completely rip it out and do something better.  I hope that makes sense.

**Comment by blackcathacker** [comment]
It does and it doesn't. It feels like we are being pure in spite of what makes sense. In this case it isn't a config, its how the project was built and if we were to release something with the grm flag on, we'd still have to re-release the entire project with it turned off, regardless of which module has the dependencies. I just want to make sure we are staying away from purity simply for the sake of purity.

**Comment by leoherbie** [comment]
no I'm not doing it for purity sake.  I'm trying to keep everything in one place for simplicity and consistency and to give less crap for the IDE to have to process.  Those are my main goals.  I'm not sure if there are any special maven rules or best practices for this.

**Comment by blackcathacker** [comment]
Ok. I can see that. It still feels cleaner to me to have a single build file, but I'm ok with this.

**Pull request merged**
