### PR TITLE
RESKC-158: more help fixes

### PR DESCRIPTION
**Pull request by gathreya**

### CODE REVIEW

**Comment by gathreya** [comment]
please do not merge before 601

**Comment by leoherbie** [comment]
please add the oracle script and add copyright headings

**Comment by gathreya** [comment]
ok, so are we going to add the license manually? There is a maven plugin we can use to autogenerate these each night.

**Comment by leoherbie** [comment]
for now manually.  We should have CI doing this for us eventually.  The header is important because any changes to the sql file causes flyway to complain

**Comment by gathreya** [comment]
ok, yeah, that's true.

**Comment by gathreya** [comment]
I'll need to rebase this after the other help PR is merged I think so please merge that before

**Comment by blackcathacker** [comment]
Needs to be rebased, as you mentioned.

**Comment by gathreya** [comment]
rebased

**Pull request merged**
