### PR TITLE
KRACOEUS-8767: Fixing help links

### PR DESCRIPTION
**Pull request by gathreya**

### CODE REVIEW

**Comment by tdurkin** [comment]
Happy to see this fixed but I thought we talked about just pointing all of the maint docs to a common doc and letting the users drill down from there.  What changed?

**Comment by gathreya** [comment]
I noticed that lots of maint docs had working links and the list of those that needed to be fixed was not as long as I originally thought so I thought it better to just fix the broken ones.

**Comment by leoherbie** [comment]
Leave it to gaya to do a better job than requested :)

**Comment by tdurkin** [comment]
I'm way ok with that answer :)

**Pull request merged**
