### PR TITLE
KRACOEUS-8875: resequence sql file

### PR DESCRIPTION
**Pull request by leoherbie**

### CODE REVIEW

**Comment by gathreya** [comment]
What happened? Were more files added?

**Comment by leoherbie** [comment]
What happened was two files were merged with the same sequence number.  When this happens flyway will fail because it doesn't know which to apply first

**Comment by gathreya** [comment]
huh, when we merged last evening, @blackcathacker and I made sure the files were sequenced right. Perhaps something was merged after we merged.

**Comment by leoherbie** [comment]
Looks like https://github.com/KualiCo/kc/pull/76 & https://github.com/KualiCo/kc/pull/83 used the same sequence.  Maybe because one was a bootstrap file and one was a demo file.

**Comment by gathreya** [comment]
Cannot wait for the jenkins job to be added.

**Comment by leoherbie** [comment]
yes we really need continuous integration.

**Pull request merged**
