### PR TITLE
KRACOEUS-8796:fix attachment errors preventing canEdit from being evalua...

### PR DESCRIPTION
**Pull request by jwillia**
...ted

### CODE REVIEW

**Comment by gathreya** [comment]
Wow. Why did the attachments disappear though? The page refreshed with 0 attachments?

**Comment by jwillia** [comment]
Only new unsaved attachments disappeared because they were never saved.  The problem was that we cleared the canEditView to recheck permissions, then if there was an error on the attachments page we just returned the user back to the page with out running permissions checks, which made it look like the user couldn't edit the page, and therefore they could not save the page either.  So then if you navigated away no of your changes would be saved, so when you came back to attachments new attachments were removed.  I changed that so that if there is an error on the attachments page it sets the canEditView back to what it was before clearing it.

**Comment by gathreya** [comment]
So when the person first added the attachments and hit "Save and Continue", those entries were not really saved?

**Comment by jwillia** [comment]
If there was an error then they wouldn't be saved, the secondary issue was that the error for no description on multi allow narrative types was not being displayed.  That is why i made the description field editable to display the error.

**Pull request merged**
